export const needPromiseApis = new Set([
  "addCardAuth",
  "getOpenUserInfo",
  "chooseAlipayContact",
  "chooseCity",
  "chooseContact",
  "choosePhoneContact",
  "datePicker",
  "getAddress",
  "getAuthCode",
  "getPhoneNumber",
  "getRunData",
  "getRunScene",
  "getServerTime",
  "getTitleColor",
  "rsa",
  "paySignCenter",
  "tradePay",
  "isCollected",
  "multiLevelSelect",
  "onLocatedComplete",
  "optionsSelect",
  "prompt",
  "regionPicker",
  "setLocatedCity",
  "showAuthGuide",
  "textRiskIdentification",
  "vibrate",
  "watchShake",
  "connectBLEDevice",
  "disconnectBLEDevice",
  "makeBluetoothPair",
  "writeBLECharacteristicValue",
  "readBLECharacteristicValue",
  "notifyBLECharacteristicValueChange",
  "getBLEDeviceServices",
  "getBLEDeviceCharacteristics",
  "openBluetoothAdapter",
  "closeBluetoothAdapter",
  "getBluetoothAdapterState",
  "startBluetoothDevicesDiscovery",
  "stopBluetoothDevicesDiscovery",
  "getBluetoothDevices",
  "getConnectedBluetoothDevices",
]);

export const needPromiseQnApis = new Set([
  // 路由
  "navigateToWebPage",
  "navigateToQAP",
  "closeQAP",
  // TabBar
  "switchTabEx",
  "showTabEx",
  "hideTabEx",
  "showTabBarRedDotEx",
  "hideTabBarRedDotEx",
  "setTabBarBadgeEx",
  "removeTabBarBadgeEx",
  // 数据库
  "queryDBSize",
  "database",
  // 文件
  "chooseFile",
  "chooseFileAndGetContent",
  "saveFileToDisk",
  // 用户授权
  "cleanToken",
  "showSubAccountAuth",
  // IM 功能
  "openChat",
  "imGetActiveUser",
  // 打开千牛组件
  "openPlugin",
  "openCategory",
  "changePrice",
]);
