import { singleQuote } from "@tarojs/shared";

export const components = {
  // ======== 调整属性 ========
  Progress: {
    size: singleQuote("medium"),
    shape: singleQuote("line"),
    percent: "0",
    state: singleQuote("normal"),
    progressive: "false",
    hasBorder: "false",
    color: "",
    backgroundColor: "",
  },
  View: {
    hidden: "false",
  },
  Text: {
    "number-of-lines": "",
  },
  Image: {
    catchTap: "eh",
  },
  Icon: {
    type: "",
    size: singleQuote("medium"),
    custom: "false",
  },
  Button: {
    size: "medium",
    type: "normal",
    iconSize: "",
    component: "button",
    loading: "false",
    ghost: "false",
    text: "false",
    warning: "false",
    disabled: "false",
  },
  Checkbox: {
    defaultChecked: "",
    indeterminate: "",
    defaultIndeterminate: "",
    bindChange: "",
  },
  CheckboxGroup: {
    disabled: "",
    dataSource: "[]",
    value: "",
    defaultValue: "",
    itemDirection: singleQuote("hoz"),
    bindChange: "",
  },
  Radio: {
    defaultChecked: "",
  },
  RadioGroup: {
    size: singleQuote("medium"),
    shape: "",
    value: "",
    defaultValue: "",
    disabled: "false",
    dataSource: "[]",
    itemDirection: singleQuote("hoz"),
  },
  Input: {
    defaultValue: "",
    size: singleQuote("medium"),
    hasLimitHint: "false",
    cutString: "true",
    readOnly: "false",
    trim: "false",
    state: "",
    hasClear: "false",
    hint: "",
    addonTextBefore: "",
    addonTextAfter: "",
    htmlType: "",
    bindChange: "",
    bindKeyDown: "",
    bindPressEnter: "",
  },
  Slider: {
    "track-size": "4",
    "handle-size": "22",
    "handle-color": singleQuote("#ffffff"),
  },
  Switch: {
    checkedChildren: "",
    size: singleQuote("medium"),
    unCheckedChildren: "",
    defaultChecked: "",
  },
  Textarea: {
    defaultValue: "",
    hasLimitHint: "false",
    cutString: "true",
    readOnly: "false",
    trim: "false",
    state: "",
    hasBorder: "true",
    rows: "4",
    bindChange: "",
    bindKeyDown: "",
  },
  MovableView: {
    bindChangeEnd: "",
  },
  // ======== 额外组件 ========
  Tab: {
    activeKey: "",
    size: singleQuote("medium"),
    shape: singleQuote("pure"),
    defaultActiveKey: "",
    animation: "true",
    excessMode: singleQuote("slide"),
    tabPosition: singleQuote("top"),
    triggerType: singleQuote("click"),
    bindChange: "",
    bindClose: "",
  },
  TabItem: {
    closeable: "false",
    disabled: "false",
    itemKey: "",
    title: "",
  },
  Overlay: {
    visible: "false",
    align: singleQuote("tl bl"),
    offset: "[0,0]",
    container: "",
    hasMask: "false",
    canCloseByEsc: "true",
    canCloseByOutSideClick: "true",
    canCloseByMask: "true",
    shouldUpdatePosition: "false",
    autoFocus: "false",
    needAdjust: "false",
    disableScroll: "false",
    cache: "false",
    safeNode: "",
    wrapperClassName: "",
    wrapperStyle: "",
    animation: "",
    bindRequestClose: "",
    bindOpen: "",
    bindClose: "",
    bindPosition: "",
  },
  Balloon: {
    type: singleQuote("normal"),
    visible: "",
    defaultVisible: "false",
    alignEdge: "false",
    closable: "",
    target: "",
    align: singleQuote("b"),
    offset: "[0, 0]",
    needAdjust: "false",
    delay: "",
    autoFocus: "true",
    animation: "",
    followTrigger: "",
    bindVisibleChange: "",
    bindClose: "",
    bindAfterClose: "",
  },
  ColorPicker: {
    color: "",
    disableAlpha: "false",
    presetColors: "",
    width: "200",
    bindChange: "",
  },
  MouseableView: {
    bindMouseover: "",
    bindMouseout: "",
    bindMouseenter: "",
    bindMouseleave: "",
    bindMouseup: "",
    bindMousedown: "",
    bindMousemove: "",
  },
  Table: {
    dataSource: "[]",
    hasBorder: "true",
    hasHeader: "true",
    isZebra: "false",
    loading: "false",
    fixedHeader: "",
    maxBodyHeight: "",
    stickyHeader: "",
    offsetTop: "",
    selectedRowKeys: "",
    mode: "multiple",
    bindChange: "",
    bindSelect: "",
    bindSelectAll: "",
    bindResizeChange: "",
    bindSort: "",
    bindFilter: "",
    bindBodyScroll: "",
  },
  Menu: {
    defaultOpenKeys: "",
    mode: singleQuote("inline"),
    triggerType: singleQuote("click"),
    openMode: singleQuote("multiple"),
    popupStyle: "",
    selectedKeys: "",
    selectMode: "",
    defaultSelectedKeys: "",
    bindItemTap: "",
    bindSelect: "",
  },
  Item: {
    disabled: "false",
    helper: "",
  },
  SubMenu: {
    selectable: "false",
    label: "",
    mode: "",
  },
  Group: {
    label: "",
  },
  MenuButton: {
    label: "",
    autoWidth: "true",
    popupTriggerType: singleQuote("click"),
    visible: "",
    defaultVisible: "",
    bindVisibleChange: "",
    bindItemClick: "",
  },
  Form: {
    inline: "false",
    size: singleQuote("medium"),
    labelAlign: singleQuote("left"),
    labelTextAlign: "",
    value: "",
    labelCol: "",
    wrapperCol: "",
    bindChange: "",
  },
  FormItem: {
    label: "",
    size: "",
    help: "",
    extra: "",
    validateState: "",
    labelAlign: "",
    labelTextAlign: "",
  },
  Select: {
    size: "",
    value: "",
    defaultValue: "",
    state: "",
    autoWidth: "true",
    readOnly: "",
    followTrigger: "false",
    disabled: "",
    dataSource: "",
    mode: "single",
    bindChange: "",
  },
  Option: {
    value: "",
    disabled: "false",
  },
  OptionGroup: {
    label: "",
  },
  Pagination: {
    size: singleQuote("medium"),
    type: singleQuote("normal"),
    shape: singleQuote("normal"),
    current: "",
    defaultCurrent: "1",
    total: "100",
    pageShowCount: "5",
    pageSize: "10",
    pageSizeSelector: "false",
    pageSizeList: "[5, 10, 20]",
    pageSizePosition: "start",
    useFloatLayout: "false",
    hideOnlyOnePage: "false",
    showJump: "false",
    bindChange: "",
    bindPageSizeChange: "",
  },
  DatePicker: {
    size: singleQuote("medium"),
    state: "",
    placeholder: "",
    value: "",
    defaultValue: "",
    format: singleQuote("YYYY-MM-DD"),
    showTime: "false",
    resetTime: "false",
    disabled: "false",
    hasClear: "true",
    visible: "",
    defaultVisible: "false",
    startDate: "",
    endDate: "",
    bindChange: "",
  },
  MonthPicker: {
    size: singleQuote("medium"),
    state: "",
    placeholder: "",
    value: "",
    defaultValue: "",
    format: singleQuote("YYYY-MM-DD"),
    disabled: "false",
    hasClear: "true",
    visible: "",
    defaultVisible: "",
    bindChange: "",
    bindVisibleChange: "",
  },
  RangePicker: {
    size: singleQuote("medium"),
    value: "",
    defaultValue: "",
    format: singleQuote("YYYY-MM-DD"),
    showTime: "false",
    resetTime: "false",
    state: "",
    disabled: "false",
    hasClear: "true",
    visible: "",
    defaultVisible: "false",
    bindChange: "",
    bindVisibleChange: "",
  },
  YearPicker: {
    size: singleQuote("medium"),
    state: "",
    placeholder: "",
    value: "",
    defaultValue: "",
    format: singleQuote("YYYY-MM-DD"),
    disabled: "false",
    hasClear: "true",
    visible: "",
    defaultVisible: "false",
    bindChange: "",
    bindVisibleChange: "",
  },
};
