import { singleQuote } from "@tarojs/shared";

export const components = {
  // ======== 调整属性 ========
  Progress: {
    size: singleQuote("medium"),
    shape: singleQuote("line"),
    percent: "0",
    state: singleQuote("normal"),
    progressive: "false",
    hasBorder: "false",
    color: "",
    backgroundColor: "",
  },
  View: {
    hidden: "false",
  },
  Text: {
    "number-of-lines": "",
  },
  Image: {
    catchTap: "eh",
  },
  Icon: {
    type: "",
    size: singleQuote("medium"),
    custom: "false",
  },
  Map: {
    skew: "0",
    rotate: "0",
    polygons: "[]",
    "include-padding": "",
    "ground-overlays": "[]",
    "tile-overlay": "",
    "custom-map-style": "",
    panels: "[]",
    setting: "{}",
    optimize: "false",
    "show-compass": "false",
    "show-scale": "false",
    "enable-overlooking": "false",
    "enable-zoom": "true",
    "enable-scroll": "true",
    "enable-rotate": "false",
    "enable-traffic": "false",
    "enable-poi": "true",
    "enable-building": "true",
    "enable-satellite": "false",
    bindRegionChange: "",
    bindPanelTap: "",
    bindInitComplete: "",
  },
  Button: {
    size: "medium",
    type: "normal",
    iconSize: "",
    component: "button",
    loading: "false",
    ghost: "false",
    text: "false",
    warning: "false",
    disabled: "false",
  },
  Checkbox: {
    bindChange: "",
  },
  Input: {
    "always-system": "false",
    "random-number": "false",
    controlled: "false",
    enableNative: "true",
    name: "",
  },
  Slider: {
    "track-size": "4",
    "handle-size": "22",
    "handle-color": singleQuote("#ffffff"),
  },
  Switch: {
    controlled: "false",
  },
  Textarea: {
    "show-count": "true",
    controlled: "false",
    enableNative: "false",
  },
  MovableView: {
    bindChangeEnd: "",
  },
  ScrollView: {
    "scroll-animation-duration": "",
    "trap-scroll": "false",
  },
  Camera: {
    mode: singleQuote("normal"),
    "output-dimension": singleQuote("720P"),
    "frame-size": singleQuote("medium"),
    bindScanCode: "",
    bindReady: "",
  },
  Canvas: {
    type: "",
    width: singleQuote("300px"),
    height: singleQuote("225px"),
    bindReady: "",
  },
  Video: {
    "poster-size": singleQuote("contain"),
    "mobilenet-hint-type": "1",
    enableNative: "true",
    bindLoading: "",
    bindUserAction: "",
    bindStop: "",
    bindRenderStart: "",
  },
  // ======== 额外组件 ========
  Tab: {
    activeKey: "",
    size: singleQuote("medium"),
    shape: singleQuote("pure"),
    defaultActiveKey: "",
    animation: "true",
    excessMode: singleQuote("slide"),
    tabPosition: singleQuote("top"),
    triggerType: singleQuote("click"),
    bindChange: "",
    bindClose: "",
  },
  TabItem: {
    closeable: "false",
    disabled: "false",
    itemKey: "",
    title: "",
  },
  Overlay: {
    visible: "false",
    align: singleQuote("tl bl"),
    offset: "[0,0]",
    container: "",
    hasMask: "false",
    canCloseByEsc: "true",
    canCloseByOutSideClick: "true",
    canCloseByMask: "true",
    shouldUpdatePosition: "false",
    autoFocus: "false",
    needAdjust: "false",
    disableScroll: "false",
    cache: "false",
    safeNode: "",
    wrapperClassName: "",
    wrapperStyle: "",
    animation: "{ in:'expandInDown', out:'expandOutUp' }",
    bindRequestClose: "",
    bindOpen: "",
    bindClose: "",
    bindPosition: "",
  },
  Balloon: {
    type: singleQuote("normal"),
    visible: "",
    defaultVisible: "false",
    alignEdge: "false",
    closable: "",
    align: singleQuote("b"),
    offset: "[0, 0]",
    needAdjust: "false",
    delay: "",
    autoFocus: "true",
    animation: "{ in: 'zoomIn', out: 'zoomOut', }",
    followTrigger: "",
    bindVisibleChange: "",
    bindClose: "",
    bindAfterClose: "",
  },
  ColorPicker: {
    color: "",
    disableAlpha: "false",
    presetColors: "",
    width: "200",
    bindChange: "",
  },
  MouseableView: {
    bindMouseover: "",
    bindMouseout: "",
    bindMouseenter: "",
    bindMouseleave: "",
    bindMouseup: "",
    bindMousedown: "",
    bindMousemove: "",
  },
  Table: {
    dataSource: "[]",
    hasBorder: "true",
    hasHeader: "true",
    isZebra: "false",
    loading: "false",
    fixedHeader: "",
    maxBodyHeight: "",
    stickyHeader: "",
    offsetTop: "",
    selectedRowKeys: "",
    mode: "multiple",
    bindChange: "",
    bindSelect: "",
    bindSelectAll: "",
    bindResizeChange: "",
    bindSort: "",
    bindFilter: "",
    bindBodyScroll: "",
  },
  Menu: {
    defaultOpenKeys: "",
    mode: singleQuote("inline"),
    triggerType: singleQuote("click"),
    openMode: singleQuote("multiple"),
    popupStyle: "",
    selectedKeys: "",
    selectMode: "",
    defaultSelectedKeys: "",
    bindItemTap: "",
    bindSelect: "",
  },
  Item: {
    disabled: "false",
    helper: "",
  },
  SubMenu: {
    selectable: "false",
    label: "",
    mode: "",
  },
  Group: {
    label: "",
  },
};
