export const needPromiseSfcApis = new Set([
  "navigateToWebPage",
  "navigateToQAP",
  "closeQAP",
  "switchTabEx",
  "queryDBSize",
  "chooseFile",
  "chooseFileAndGetContent",
  "saveFileToDisk",
  "cleanToken",
  "showSubAccountAuth",
  "openChat",
  "imGetActiveUser",
  "openPlugin",
  "openCategory",
  "changePrice",
]);
